name:                web
version:             0.1.0.0
github:              "githubuser/web"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/web#readme>

dependencies:
- base >= 4.7 && < 5
- network 
- scotty
- text
- aeson
- http-types
- postgresql-simple
- transformers
- bytestring
- wai-extra
- directory
- filepath
- jwt
- dotenv
- unordered-containers
- time
- containers
- bcrypt

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs:
    - src
  other-modules:
    - Auth.Jwt
    - Helpers.Config
    - Helpers.Helper
    - Helpers.HashPassword
    - Models.AuthLib
    - Models.ProductLib
    - Models.Result
    - Models.UserLib
    - Models.PayloadLib
    - Rest.AuthAPIs
    - Rest.Check
    - Rest.ProductAPI
    - Rest.Upload
    - Rest.Login
    - Rest.Signup
    - Auth.Token


executables:
  web-exe:
    main:                Main.hs
    source-dirs:
    - app
    - src
    - src/Rest
    - src/Models
    - src/Helpers
    - src/Auth
    other-modules:
      - Auth.Jwt
      - Helpers.Config
      - Helpers.Helper
      - Helpers.HashPassword
      - Models.AuthLib
      - Models.ProductLib
      - Models.Result
      - Models.UserLib
      - Models.PayloadLib
      - Rest.AuthAPIs
      - Rest.Check
      - Rest.ProductAPI
      - Rest.Upload
      - Rest.Login
      - Rest.Signup
      - Auth.Token
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - web

tests:
  web-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - web
